server:
  port: 9080
spring:
  application:
    name: cloud-payment-service
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver    #数据库驱动
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: xuziwei520